# Generated by Django 2.0.7 on 2018-09-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_music_album_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='Album_art',
            field=models.ImageField(default='', upload_to='music/albumart'),
        ),
    ]
