# Generated by Django 2.0.7 on 2018-09-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0003_auto_20180907_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='Album_art',
            field=models.ImageField(blank=True, default='', null=True, upload_to='music/albumart'),
        ),
    ]
