# Generated by Django 2.0.7 on 2018-09-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0004_auto_20180908_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='Album_art',
            field=models.URLField(blank=True, default=''),
        ),
    ]
