# Generated by Django 2.0.7 on 2018-09-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0005_auto_20180908_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='Server_img',
            field=models.ImageField(default='', upload_to='music/albumart'),
        ),
    ]
